[package]
name = "aariba"
version = "0.1.0"
authors = ["Vaelden <maugan.villatel@gmail.com>"]
build = "build.rs"

[dependencies]
log = "0.3.6"
rand = "0.3.14"
lalrpop-util = "0.11.0"
ordered-float = "0.2.1"

[build-dependencies]
lalrpop = "0.11.0"
